streams:
  kafkaBroker: localhost:9092
  applicationId: preprocessor

  consumer:
    topic:
      name: all_messages
    autoOffsetReset: earliest

  producer:
    topic:
      name: filtered_messages
      partitions: 3

preprocessor:
  keywords:
    - Welcome
    - to
    - SumUp
    - coding
    - challenge

  common:
    - a
    - and
    - for
    - I
    - by
    - of
    - on
    - is
    - as

  delimiters:
    - "-"
    - "!"
    - " "
    - ","
    - "."
    - "?"
    - "("
    - ")"



